### ISSUE TITLE
DB schema review

### ISSUE THREAD

**Issue by javiermortiz** [alpvyas/code-hunt#1]
Great job team! A couple of recommendations:
- The comments table is missing the videoId (which you do have in the image available in slack).
- You might want to include an image url for the product profile page not just the video. Same for users.
- Even though collections and upvotes are bonus features it might be worth to talk about them and how those table would fit / relate to the other tables in your schema.

**Comment by W-the-V** [comment]
Thank you for these recommendations. I have fixed the comments table to include the videoId. With our idea, we were going to have a description of the video replace the image of the product as we were switching the idea to be about links to programming videos instead of links to potential products. The product hunt website has images/videos displaying the product with a link on the right hand side to the product with a description listed as a comment posted by the owner. We thought it would make sense for our implementation to be a Description of the video replacing the images/videos of the product while putting a direct link to the video where the Product Hunt - Get Product button is. Would this implementation be valid? There is definitely the option of a profile picture on the profile page, we were thinking of omitting this feature. I'm not entirely sure how to implement the uploading of profile pictures to a database, is that somewhere in the a/A readings, or will it be in a reading for the upcoming week? Thank you for your time.

**Comment by javiermortiz** [comment]
Thanks for the quick reply. If I'm understanding correctly instead of having a video you'll have the description, and instead of the get product button you'll have a button to take you to the link. It is definitely a valid implementation. I'd still encourage to keep in the backlog the idea of adding a picture to each product. It is a cool way to make the site look more polished. There are no aA readings for this as far as I know. Feel free to omit it and if you feel you are making good progress and would like to implement it we could research it together, same for users' profile picture. 

The schema looks good, this is me giving you the green light with the schema. Make sure to check in with JM for the green light on the feature list, user stories and routes.
